# Generated by Django 5.1.1 on 2024-10-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_streamingserviceaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingserviceaccount',
            name='verfied',
            field=models.BooleanField(default=False),
        ),
    ]
