# Generated by Django 5.1.1 on 2024-10-16 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_screensubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screensubscription',
            name='payment_status',
            field=models.CharField(choices=[('N', 'Not Initiated'), ('P', 'Pending'), ('C', 'Completed')], default='N', max_length=50),
        ),
        migrations.AlterField(
            model_name='screensubscription',
            name='streaming_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen', to='api.streamingserviceaccount'),
        ),
    ]
